version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 415782
    volumes:
      - checkmate:/var/lib/postgresql

volumes:
  checkmate: